apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://github.com/cloudbeer/cd-script.git"
    targetRevision: HEAD
    path: gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
