apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  annotations:
<<<<<<< HEAD
    notifications.argoproj.io/subscribe.on-sync-succeeded.swire: dongzhuoming2018@gmail.com
    notifications.argoproj.io/subscribe.on-sync-failed.swire: dongzhuoming2018@gmail.com
    notifications.argoproj.io/subscribe.on-sync-status-unknown.swire: dongzhuoming2018@gmail.com
=======
    notifications.argoproj.io/subscribe.on-sync-succeeded.gmail: dongzhuoming2018@gmail.com
    notifications.argoproj.io/subscribe.on-sync-failed.gmail: dongzhuoming2018@gmail.com
    notifications.argoproj.io/subscribe.on-sync-status-unknown.gmail: dongzhuoming2018@gmail.com
    notifications.argoproj.io/subscribe.on-deployed.gmail: cloudbeer@hotmail.com
>>>>>>> 689fc9e (update ingress)
spec:
  project: default
  destination:
    namespace: test
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://github.com/swire-aws/cd-script.git"
    targetRevision: HEAD
    path: nginx
  syncPolicy:
    automated: {}
  # prune: true
  # selfHeal: true
