apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.swire: dongzhuoming2018@gmail.com
    notifications.argoproj.io/subscribe.on-sync-failed.swire: dongzhuoming2018@gmail.com
    notifications.argoproj.io/subscribe.on-sync-status-unknown.swire: dongzhuoming2018@gmail.com
spec:
  project: default
  destination:
    namespace: test
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://github.com/swire-aws/cd-script.git"
    targetRevision: HEAD
    path: nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
