apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: nginx
commonLabels:
  app: nginx
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: nginx
    newTag: "1.20"
